layout_spectrum: 0.257827
typography_spectrum: 0.9486614
color:
  lightness: 0.1172462
  brandStrength: 0.7092463
  saturation: 0.3992242
  rhythmicContrast: 0.2428674
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Uniquely You
